client_id = "53f8ae132fda7c8688b4f7202aa5b6c3"
name = "countdownboost"
application_url = "https://dictionaries-oils-ambassador-production.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/customers/data_request"

[access_scopes]
scopes = "write_products,write_metaobjects,write_metaobject_definitions"

[auth]
redirect_urls = [ "https://dictionaries-oils-ambassador-production.trycloudflare.com/api/auth" ]